### ISSUE TITLE
System UI crash on cm13

### ISSUE THREAD

**Issue by Tatguy7** [ztc1997/HideableNavBar#7]
Running latest cm13 on nexus 6p

**Comment by Maartenwut** [comment]
+1

**Comment by char101** [comment]
Logcat

```
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.android.systemui, PID: 2424
E AndroidRuntime: Theme: themes:{default=, fontPkg:org.cyanogenmod.hexolibre, com.android.systemui.navbar=overlay:org.cyanogenmod.hexolibre}
E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.statusbar.policy.KeyButtonView.setInfo(com.android.systemui.statusbar.phone.NavbarEditor$ButtonInfo, boolean, boolean)' on a null object reference
E AndroidRuntime: 	at com.android.systemui.statusbar.phone.NavbarEditor.<init>(NavbarEditor.java:167)
E AndroidRuntime: 	at com.android.systemui.statusbar.phone.NavigationBarView.reorient(NavigationBarView.java:622)
E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBar.prepareNavigationBarView(PhoneStatusBar.java:1583)
E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBar.addNavigationBar(PhoneStatusBar.java:1612)
E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:825)
E AndroidRuntime: 	at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
E AndroidRuntime: 	at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
E AndroidRuntime: 	at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:230)
E AndroidRuntime: 	at com.android.systemui.statusbar.ServiceMonitor.-wrap5(ServiceMonitor.java)
E AndroidRuntime: 	at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```
